# Generated by Django 5.0.1 on 2024-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_18_plus',
            field=models.BooleanField(default=False),
        ),
    ]
