# Generated by Django 4.2.10 on 2024-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_number',
            field=models.IntegerField(default=0),
        ),
    ]
