# Generated by Django 4.2.10 on 2024-02-29 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_store_storeinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(through='products.StoreInventory', to='products.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='inventory',
            field=models.ManyToManyField(through='products.StoreInventory', to='products.product'),
        ),
    ]
