# Generated by Django 4.2.10 on 2024-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_display_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='extra_column',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
