# Generated by Django 4.2.10 on 2024-03-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderproduct_extra_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='extra_column',
        ),
    ]
